### ISSUE TITLE
Error on specifying `verbose=True` to `cfp.con` 

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-plot#54]
`verbose` is a valid keyword to the `cfp.con` function (though not to other plotting functions, the inconsistency of which is a problem in itself), but it currently raises an error that is obscure to the user, e.g. as per this snippet from the docs with `verbose` added into the mix:

```python
>>> f = cf.read("../cfplot_data/tas_A1.nc")[0]
>>> cfp.con(f.subspace(time=15))  # works fine
>>> cfp.con(f.subspace(time=15), verbose=True)
con - calling cf_data_assign
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slb93/git-repos/cf-plot/cfplot/cfplot.py", line 789, in con
    cf_data_assign(f, colorbar_title, verbose=verbose)
  File "/home/slb93/git-repos/cf-plot/cfplot/cfplot.py", line 4646, in cf_data_assign
    print("time -", mydim)
                    ^^^^^
UnboundLocalError: cannot access local variable 'mydim' where it is not associated with a value
>>> exit()
```

**Comment by sadielbartholomew** [comment]
Fixed by 97175aa2680fc1e3ea7f8ea618c27e8f8cc0b1a0, so closing.
