### ISSUE TITLE
Stipple plot call failure with `AttributeError` due to `NoneType` `mymap`

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-plot#9]
A pair of users have reported, for the same dataset, that the `stipple` method is erroring as follows:

```pytb
cfp.stipple(g, min=0.2, max=0.9, size=100, color='#00ff00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/apps/NCAS/anaconda3/lib/python3.7/site-packages/cfplot/cfplot.py", line 4227, in stipple
    plotvars.mymap.scatter(xnew[valid_points], ynew[valid_points],
AttributeError: 'NoneType' object has no attribute 'scatter'
```

I have asked for further details and will note anything significant on this thread; the specific case in which this emerges is still under investigation.

**Comment by sadielbartholomew** [comment]
> I have asked for further details and will note anything significant on this thread; the specific case in which this emerges is still under investigation.

It has emerged since that this bug was occurring for a previous version of cf-plot and has since been fixed for the latest version. Hence, closing.
